### ISSUE TITLE
Make a "Report an issue..." menu button

### ISSUE THREAD

**Issue by acenturyandabit** [acenturyandabit/polymorph#14]
Put it as a menu item under the (currently empty) "help" menu on the upper toolbar.

You'll have to wrangle with `topbar.js` which isn't documented suuper well (sorry) but you can learn the syntax off of the New and Load/Save buttons! 

Extra thanks if you add some documentation to `topbar.js` so the next person to work on the topbar can see what's going on.

**Comment by kjng** [comment]
What's the desired functionality of this button? Open up an email compose screen?

**Comment by acenturyandabit** [comment]
Sure, email sounds like a good idea. Compose to steeven.liu2@gmail.com. Thanks!
