### ISSUE TITLE
Replace innerHTML=

### ISSUE THREAD

**Issue by acenturyandabit** [acenturyandabit/polymorph#18]
A profile check shows that innerHTML=etc calls are causing lag.

Your mission, if you choose to accept it, is to hunt down as many innerHTML sets and eliminate them.

**Comment by JordanRosas** [comment]
I would like to look into this issue can you please assign it to me?

**Comment by acenturyandabit** [comment]
done :) thanks

**Comment by victoriatomzik** [comment]
Is it done? Can the issue be closed?

**Comment by acenturyandabit** [comment]
nope, still plenty to do here...

**Comment by silkie261001** [comment]
I want to see this issue can you please assign it to me

**Comment by acenturyandabit** [comment]
Sure, you're welcome to take a look

**Comment by jwardoin** [comment]
Is this completed? If not, I'd like to help!

**Comment by acenturyandabit** [comment]
Alrighty, sure!

**Comment by jwardoin** [comment]
> Alrighty, sure!

Okay, I would like some clarity if possible - do you want instances of innerHTML completely eliminated or rather replaced with some like innerText(depending on context)?

**Comment by acenturyandabit** [comment]
I've had a closer look at the issue, and I use innerHTML some 163 times throughout the project. I think all of the times I used it it's just for string literals, so no chance of xss or any nasties. Looks like this actually isn't an issue 😅 

Thanks for taking a look! I'll close this one now :)
