### ISSUE TITLE
Enter automatically creates new document on file screen

### ISSUE THREAD

**Issue by acenturyandabit** [acenturyandabit/polymorph#27]
To produce: 
1. Click the save icon and press open.
2. Type in a new document name into the textbox.
3. Press enter.

Expected behaviour: This takes you to a new document just like the new doc button.

Actual behaviour: *crickets*

**Comment by fredunit** [comment]
@acenturyandabit I want to make it #27, could you help me how to do it?

**Comment by acenturyandabit** [comment]
Hey Fred, 
Yes, I can, but I will warn you that I want to deprecate filescreen in the near future in favour of a VS-code like open screen.  If you want to do that, then you need to create an operator (see operators/template.js) that implements filescreen's operations. Otherwise, to continue on this issue: 

1. Go to versions/filescreen.js
2. Isolate the input element.
3. Add an eventlistener for keydown; check the key is enter; and if so, fire a click() on the button. (Or call the function directly).

I hope that's granular enough for you. Give it a try and let me know how you go?

**Comment by fredunit** [comment]
This is what I get from your suggestion.
`document.addEventListener ("keydown", function(event)
 {if(key === 13) {return document.getElementsByClassName("button").click();}
});`

**Comment by acenturyandabit** [comment]
Haha not quite mate, you'll have to find out exactly which button it is. And where to put the lines that you've given me. :)

**Comment by acenturyandabit** [comment]
The loading screen has completely changed. This issue is no longer relevant.
