### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by lukenavo** [acenturyandabit/polymorph#33]
Hi, I'm trying to use polymorph on my pc. I just extract the zipped file and run index.html with firefox.
It seems work but when I try to add mind map it didn't work at all. If I double click with left mouse button no one concept start.
Is it necessary to upload in a web server?
Is it possible to change the sky picture on the ground?
Sorry for these dummies question.
Thank you

**Comment by acenturyandabit** [comment]
Hi @lukenavo! This seems to be a firefox soecific issue and i have fixed it. Thanks for raising it!

I have not yet built a feature to change the sky background. I will create an issue for this.
