### ISSUE TITLE
Prompt for save on exit

### ISSUE THREAD

**Issue by acenturyandabit** [acenturyandabit/polymorph#4]
When the user exits, they may have made edits which are not yet saved. 

Steps:
1. Create a core.saveprompt.js file and include it in index.html.
2. Catch the `updateItem` event and change a 'item edited' flag
3. Catch user close and fire a `beforeunload` event which prompts save.

**Comment by TorRydberg** [comment]
I'd like to take a shot at this, do I need and permissions to cut a branch?

**Comment by acenturyandabit** [comment]
Hey Tor! I've actually already done this :/ sorryy but yes for future reference:
1. Click Fork. This will create a copy of my project in your repos.
2. Make changes and push to YOUR repo.
3. In THIS repo, click 'Pull requests' and create a pull request based on your fork...
I think. I've got to be honest, I haven't done anything more complicated than editing readme.md's directly in the master repo yet. 

I'll get back to you the next time I create an issue with a similar difficulty level. Thanks fro your interest!
