### ISSUE TITLE
Phone workflowish right-click menu can't copy text

### ISSUE THREAD

**Issue by acenturyandabit** [acenturyandabit/polymorph#41]

**Comment by VelialCypher** [comment]
Hello!
Сan i help u with fixing this task?

**Comment by acenturyandabit** [comment]
Hi, thanks for the offer! This has actually been fixed haha, I really ought to spend more time maintaining the issues...

I am actually closing this repo soon in favour of a rewrite which will significantly improve the code quality. If you want to help on something immediately, why not check out https://github.com/acenturyandabit/fortknight?

**Comment by VelialCypher** [comment]
Heh, no problem :)
I'll take a look at Fortknight.
